name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed -n "TeacherWorkloadCalculator" .\teacher_workload.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TeacherWorkloadCalculator.exe
          path: ./dist/TeacherWorkloadCalculator.exe
        
